# backend/app/models/__init__.py
from app.models.base import Base
from app.models.document import Document, DocumentStatus, SignatureType, FolderType, StampMapping, CustomFolder
from app.models.employee import Employee, EmployeeRoleEnum, DocumentReview
from app.models.user import User, AdminUser
from app.models.vacancy import Vacancy, POSITION_CLASSIFIER, is_teacher_position
from app.models.school_class import SchoolClass
from app.models.program import EducationalProgram
from app.models.mail import MailMessage, MailDirection, MailStatus, Organization, Contact, License
from app.models.appeal import (
    Appeal, AppealAttachment, AppealStatusHistory, AppealDocumentLink,
    AppealKind, AppealApplicantType, AppealStatus,
    AppealReplyType, AppealReplyFormat, AppealReplyState, ResponseTemplate,
)
from app.models.pydantic import (
    DocumentCreate,
    DocumentUpdate,
    DocumentResponse,
    SignatureVerifyRequest,
    SignatureVerifyResponse,
    PaginatedResponse,
    GoskeyData,
    VisualizeRequest,
    LoginRequest,
    TokenResponse,
    RefreshRequest,
    OrgInfoResponse,
    LicenseInfo,
    ContactCreate,
    ContactUpdate,
    ContactResponse,
    ContactPaginatedResponse,
    MailMessageCreate,
    MailMessageResponse,
    MailPaginatedResponse,
    OrganizationResponse,
    EmployeeCreate,
    EmployeeUpdate,
    EmployeeResponse,
    EmployeeLoginResponse,
    EmployeeRoleInfo,
    ProfileCompleteRequest,
    VacancyCreate,
    VacancyUpdate,
    VacancyResponse,
    VacancyPaginatedResponse,
    VacancyPositionInfo,
    VacancyPositionListResponse,
    SchoolClassCreate,
    SchoolClassUpdate,
    SchoolClassResponse,
    SchoolClassPaginatedResponse,
    SchoolClassOption,
    SchoolClassOptionsResponse,
    SchoolClassTeacher,
    SchoolClassTeacherListResponse,
    ProgramCreate,
    ProgramUpdate,
    ProgramResponse,
    ProgramPaginatedResponse,
    ProgramOptionsResponse,
    ProgramClassItem,
    ProgramClassListResponse,
    ProgramClassAssignRequest,
)

__all__ = [
    "Appeal",
    "AppealAttachment",
    "AppealStatusHistory",
    "AppealDocumentLink",
    "AppealKind",
    "AppealApplicantType",
    "AppealStatus",
    "AppealReplyType",
    "AppealReplyFormat",
    "AppealReplyState",
    "ResponseTemplate",
    "Base",
    "Document",
    "DocumentStatus",
    "SignatureType",
    "FolderType",
    "StampMapping",
    "CustomFolder",
    "Employee",
    "EmployeeRoleEnum",
    "DocumentReview",
    "User",
    "AdminUser",
    "Vacancy",
    "POSITION_CLASSIFIER",
    "is_teacher_position",
    "MailMessage",
    "MailDirection",
    "MailStatus",
    "Organization",
    "Contact",
    "License",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "SignatureVerifyRequest",
    "SignatureVerifyResponse",
    "PaginatedResponse",
    "GoskeyData",
    "VisualizeRequest",
    "LoginRequest",
    "TokenResponse",
    "RefreshRequest",
    "OrgInfoResponse",
    "LicenseInfo",
    "ContactCreate",
    "ContactUpdate",
    "ContactResponse",
    "ContactPaginatedResponse",
    "MailMessageCreate",
    "MailMessageResponse",
    "MailPaginatedResponse",
    "OrganizationResponse",
    "EmployeeCreate",
    "EmployeeUpdate",
    "EmployeeResponse",
    "EmployeeLoginResponse",
    "EmployeeRoleInfo",
    "ProfileCompleteRequest",
    "VacancyCreate",
    "VacancyUpdate",
    "VacancyResponse",
    "VacancyPaginatedResponse",
    "VacancyPositionInfo",
    "VacancyPositionListResponse",
    "SchoolClass",
    "SchoolClassCreate",
    "SchoolClassUpdate",
    "SchoolClassResponse",
    "SchoolClassPaginatedResponse",
    "SchoolClassOption",
    "SchoolClassOptionsResponse",
    "SchoolClassTeacher",
    "SchoolClassTeacherListResponse",
    "EducationalProgram",
    "ProgramCreate",
    "ProgramUpdate",
    "ProgramResponse",
    "ProgramPaginatedResponse",
    "ProgramOptionsResponse",
    "ProgramClassItem",
    "ProgramClassListResponse",
    "ProgramClassAssignRequest",
]
